### PR TITLE
Added shadow

### PR DESCRIPTION
**Pull request by domness**
The ViewController may now cast a shadow on the left sidebar. Uses QuartzCore and the UIView layer to create the shadow.

### CODE REVIEW

**Comment by andreyanisimov** [comment]
Thanks for the great project! I figured out how to significantly improve performance of the shadow:

```
self.view.layer.masksToBounds = NO;
self.view.layer.shadowRadius = 10;
self.view.layer.shadowOpacity = 0.5;
self.view.layer.shadowColor = [[UIColor blackColor] CGColor];
self.view.layer.shadowOffset = CGSizeZero;
self.view.layer.shadowPath = [[UIBezierPath bezierPathWithRect:self.view.bounds] CGPath];
```

**Comment by jamztang** [comment]
@andreyanisimov Thanks! The performance is largely improved while using shadowPaths. However as apple doc said,

`Unlike most animatable properties, shadowPath (as with all CGPathRef animatable properties) does not support implicit animation.`

We'd also needed to make sure it would update on orientation changes/view bounds changes, any ideas?

**Comment by andreyanisimov** [comment]
What about changing the shadowPath explicitly each time the orientation changes?

**Comment by jamztang** [comment]
I think we'd need to encapsulate that into somewhere and never bother the current view controller for the shadow configuration, or else we'd needed to handle this in every view controllers we implement.

**Comment by devinfoley** [comment]
It would be great to get this in master (and pods).

**Pull request closed without merging**
