### PR TITLE
added 2 delegate methods for above/below insertion

### PR DESCRIPTION
**Pull request by boecko**
(viewForLeftSidebarAbove, viewForRightSidebarAbove) so you can choose the insertion method.

No i can can use a drop shadow on the SideBarView

### CODE REVIEW

**Comment by jamztang** [comment]
Hi @boecko,

I've tried your patch and the sidebar just throw into the view suddenly, which doesn't quite match the revealing animation. Would you mind describing the use cases?

**Comment by boecko** [comment]
Okay .. thats right. …
the use case is, that the sidebar should be visually over the main-UITableView.
see
https://raw.github.com/gist/3938719/a3c41f033271af675cb839bc66483e138b3dac4e/dropshadow.png

So basically, my code is missing an insertion animation.

**Comment by jamztang** [comment]
I'm afraid this stage it doesn't look complete to me. Btw, please kindly use a new feature branch from master instead of development, that would be better for me to do direct merging :)

**Comment by boecko** [comment]
as I said … 

"So basically, my code is missing an insertion animation."  ;)

ok .. I'll be back :109:

**Pull request closed without merging**
